openapi: 3.0.0
info:
  title: MiniBlog API - Proyecto Integrador M2
  description: API REST para gestionar autores, publicaciones y comentarios literarios.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor Local

paths:
  /authors:
    get:
      summary: Listar todos los autores
      responses:
        '200':
          description: Lista de autores obtenida con éxito.
    post:
      summary: Crear un nuevo autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: {type: string}
                email: {type: string}
                bio: {type: string}
      responses:
        '201':
          description: Autor creado.
        '400':
          description: Datos inválidos o email duplicado.

  /posts:
    get:
      summary: Listar todos los posts
      responses:
        '200':
          description: Lista de posts.
    post:
      summary: Crear un nuevo post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author_id: {type: integer}
                title: {type: string}
                content: {type: string}
      responses:
        '201':
          description: Post creado.

  /comments:
    post:
      summary: Crear un comentario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post_id: {type: integer}
                author_id: {type: integer}
                content: {type: string}
      responses:
        '201':
          description: Comentario creado.

  /health:
    get:
      summary: Verificar estado de la API
      responses:
        '200':
          description: API funcionando.