openapi: 3.1.1
info:
  title: MiniBlog API - Proyecto Integrador M2
  description: API REST para gestionar autores, publicaciones y comentarios literarios.
  version: 1.0.0
  contact:
    name: Fernanda Posada García
    email: ferposadagarcia@gmail.com
servers:
  - url: http://localhost:3000
    description: Servidor de Desarrollo

paths:
  /healths:
    get:
      summary: Estado de la API
      responses:
        '200':
          description: API funcionando.
  /authors:
    get:
      summary: Listar todos los autores
      responses:
        '200':
          description: Lista de autores
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Author'
    post:
      summary: Crear un nuevo autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorInput'
            example:
              name: "Milan Kundera"
              email: "milan@kundera.cz"
              bio: "Escritor checo, autor de 'La insoportable levedad del ser"
      responses:
        '201':
          description: Autor creado.
        '400':
          $ref: '#/components/responses/BadRequest'
  /authors/{id}:
    parameters:
      - $ref: '#/components/parameters/Id'
    get:
      summary: Obtener detalles de un autor  
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Actualizar información de un autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorInput'
      responses:
        '200':
          description: Autor actualizado.
        '404':
          $ref: '#/components/responses/NotFound'      
    delete:
      summary: Eliminar un autor y sus posts/comentarios asociados
      responses:
        '204':
          description: Autor eliminado correctamente.  
  /posts:
    get:
      summary: Listar todos los posts
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Crear un nuevo post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
            example:
              title: "La insoportable levedad del ser"
              content: Un ensayo sobre el peso de las desiciones.
              author_id: 1
              published: true
      responses:
        '201':
          description: Post creado.
  /posts/authors/{authorId}:
    parameters:
      - name: authorId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Listar posts de un autor específico
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostWithAuthor'
    delete:
      summary: Eliminar todos los posts de un autor específico
      responses:
        '204':
          description: Posts eliminados correctamente.
  /comments:
    post:
      summary: Crear un comentario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        '201':
          description: Comentario creado.
  /comments/posts/{postId}:
    parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Ver comentarios de un post
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentWithAuthor'
                  